### ISSUE TITLE
cf_mocap: TF_NAN_INPUT in transform between optitrack and cf/odom

### ISSUE THREAD

**Issue by bgromov** [jeguzzi/drone_arena#1]
The following error appears from time to time when the Crazyflie is powered on. It typically happens after replacing a battery.

```
Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "cf/odom" from authority "/filtered_optitrack" because of a nan value in the transform (nan nan nan) (0.070818 0.221377 0.624411 0.745713)
```

The `/optitrack/cf` is ok and has no NaNs

Sometimes it helps to just power cycle the Crazyflie. Otherwise the `cf_mocap` container has to be restarted.

**Comment by jeguzzi** [comment]
Solved by validating odometry values before publishing a tf transform (as the cf may stream garbage): https://github.com/jeguzzi/optitrack_odom/commit/edea598f325232f4cd641ecd54a2029e0d5888e7 and https://github.com/jeguzzi/crazyflie_ros/commit/39d96ecb0aadfe706732af907929b22e5638353b
